INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(19, 'AT', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(20, 'BE', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(21, 'BG', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(22, 'HR', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(23, 'CY', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(24, 'CZ', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(25, 'DK', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(26, 'EE', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(27, 'FI', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(28, 'FR', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(29, 'DE', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(30, 'GR', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(31, 'HU', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(32, 'IE', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(33, 'IT', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(34, 'LV', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(35, 'LT', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(36, 'LU', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(37, 'MT', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(38, 'NL', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(39, 'PL', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(40, 'PT', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(41, 'RO', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(42, 'SK', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(43, 'SI', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(44, 'ES', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(45, 'SE', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(46, 'MC', 1);
INSERT INTO dbzoll.Countries
(Id, A2Code, isEUCU)
VALUES(47, 'SM', 1);
